name: Test Main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test/

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test python
        run: |
          pytest -vv
          pytest --cov --cov-fail-under=90
      - name: Lint python
        run: ruff check --output-format=github .